# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 918286a16c1e5a46fd4d9757f057f314f0005ca40d4395d27c72a13c0bca2b92ac1a4a99016bf5f8123f7dc0f3bb9efab0768bc606062b810e5eec3009c43ef1

test:
  secret_key_base: 8b314f6dacaba2f0611475c32cbd3355e643add161a6e6a815c3c560319d9a7531bdf476cf7e02941de0e2e4e285fce455e29ec73dc910d0508b54fc7db440bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
